# Neural Network

Nel campo dell'**Intelligienza Artificiale** (_AI_) le **Neural Network** (_NN_) rappresentano
uno degli approcci principali per permettere di compiere a sistemi automatici dei
task molto complessi e articolati che algoritmi classici (sequenziali) non sarebbero in grado di portare a termine se non con un grado di complessità elevato.

Le basi di questo nuovo approccio risalgono alla metà del XIX secolo quando per la prima volta furono proposti algoritmi per l'apprendimento automatico. Obiettivo di questo nuovo tipo di approccio era quello di creare _strutture_ in grado di modellare un determinato fenomeno e riproporne il comportamento sotto determinate condizioni.

Unità base di questa nuova struttura è il _**neurone**_. Con questo termine identifichiamo un oggetto in grado di simulare il comportamento di un neurone classico e di interconnettersi con altri per creare una rete. La gestione di queste uscite e di queste interconnessioni è stabilita dall'algoritmo di training che ha guidato la rete nella fase di addestramento appunto.

È curioso notare come la prospettiva iniziale di questo approccio era quella di creare macchine intelligienti, in grado di auto apprendere e riuscire ad eseguire in maniera intelligente i task che vengono sottomessi.

Un tipico esempio di struttura base di queste reti è il **percettrone**
![Percettrone](./img/percetrone.png)

Ogni singolo ingresso rappresenta il contributo che viene fornito da una particolare caratteristica del fenomeno atto dell'analisi. Tutti questi contributi apportano, in maniera pesata, il proprio apporto verso la particolare funzione di trasferimento del sistema, la cui uscita, in combinazione con una determinata funzione di attivazione, viene riportata al di fuori del sistema e rappresenta il valore interpretato dal neurone in base agli ingressi forniti.

Ponenedo in cascata e combinando tra loro più percettroni (o più genericamente più neuroni) generiamo quella che definiamo rete neurale
![ANN](./img/ann.png)

Nel corso degli anni l'interesse rivolto a questa nuova metodologia è andato via via scemando. Di pari passo però altri hanno proseguito lo studio delle reti neurali dandovi un taglio più matematico e sistemico grazie all'avvento di nuove metodologie come il **machine learinig**.


Grazie a questo nuovo tipo di approccio, i modelli attuali di reti neurali risultano molto più complessi e performanti dei loro antenati. A partire dalla metà degli anni 80 del secolo scorso, il campo dell'intelligineza arificiale, avendo acquisito maggiore autorevolezza e rigore scientifico, è diventato uno dei più floridi terreni di ricerca. I risultati e i campi applicativi acquisiscono, di giorno in giorno, sempre maggiore interesse. Siamo così passati ad analizzare, attraverso le reti neurali, problemi sempre più complessi: è l'avvento del **deep learning**.

Nelle reti neurali classiche moderne è possible riscontrare la presenza di qualche strato nascoto. Questi strati, denominati _hidden layers_, possono essere interpretati come il _cuore_ della rete stessa pocihé sono quelli che si occupano di interpretare le features sottomesse alla rete.

![NN](./img/simple_neural_network_header.jpg)

Con il deep learning, invece, siamo rapportati a problemi più complessi: _dal riconoscimento ed interpretazione del linguaggio naturale fino alla visione artificiale_. Nei modelli deep ogni singolo starto nascosto potrebbe essere paragonato ad una piccola rete neurale classica: ponenondone in cascata una all'altra possiamo ottnere modelli complessi per la gestione di task anche molto avanzati come ad esempio gli algoritmi di visione per l'_automotive_

![deep](./img/deep.png)

#### Codice utlizzato per la Neural Network del caso di studio

In [9]:
# standard libraries
import os
import shutil
import numpy as np
from keras.callbacks import TensorBoard, EarlyStopping, ModelCheckpoint
from keras.layers import Dense, Dropout
# keras libraries
from keras.models import Sequential
from keras.models import load_model
from keras.utils import np_utils
from sklearn import preprocessing
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.model_selection import KFold

# project libraries
from src.nn.keras_nn import load_data_nn

# convolutional network parmas
path_dataset = './dataset/dataset_total.txt'  # datasetpath
path_best = './best_model/'  # kfolds model path
path_thebest = './thebetter_model/'  # bset models path

# neural network params
batch_size = 32  # training cases batch
num_epochs = 500  # max number of epochs
num_classes = 3  # number of class in dataset
seed = 42  # base random seed
n_splits = 10  # number of kfold
n_input_layer = 31 # number of inputs layer

In [10]:
def load_data_nn():
    """
    generate dataset based on data in dataset folder
    :return: train and test dataset based on stratification strategy
    """
    dataset = np.loadtxt(path_dataset, delimiter='\t')

    y = np.array(np.ceil(dataset[:, -1])).astype(np.str)
    X = np.array(dataset[:, :-1]).astype(np.float32)

    x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=seed, stratify=y)

    scaler = preprocessing.StandardScaler().fit(x_train)

    X_train = scaler.transform(x_train)
    X_test = scaler.transform(x_test)

    y_train = np.subtract(y_train.reshape((len(y_train), 1)).astype(np.float32), np.asarray(2.0))
    y_test = np.subtract(y_test.reshape((len(y_test), 1)).astype(np.float32), np.asarray(2.0))

    Y_train = np_utils.to_categorical(y_train, num_classes)
    Y_test = np_utils.to_categorical(y_test, num_classes)
    return X_train, X_test, Y_train, Y_test

In [12]:
def baseline_model():
    """
    Definition of neural network base model
    :return: model
    """
    base_model = Sequential()
    base_model.add(Dense(n_input_layer, activation='elu',  input_shape=(X_train.shape[1],)))
    #hidden
    base_model.add(Dense(31, activation='elu'))
    base_model.add(Dropout(0.1))
    base_model.add(Dense(31, activation='elu'))
    base_model.add(Dropout(0.1))
    base_model.add(Dense(31, activation='elu'))
    base_model.add(Dropout(0.1))
    base_model.add(Dense(31, activation='elu'))
    base_model.add(Dropout(0.3))
    base_model.add(Dense(3, activation='softmax'))
    base_model.compile(optimizer='adadelta', loss='binary_crossentropy', metrics=['accuracy'])
    return base_model

In [13]:
def evaluete_nn(X_test, Y_test, best_model):
    """
    Evaluate best model after kfold training
    :param X_test: example images to test best model after kfold
    :param Y_test: labels matching truth to example
    :param best_model: index which identify best model after kfold
    :return: evaluation of best model trough dataset test and save it with loss and accuracy metrics
    """

    # load best model and evaluate it with accuracy and loss
    print('Load best model and test it ')
    model = load_model(path_best+'checkpoint-%d.h5' %(best_model))
    score = model.evaluate(X_test, Y_test, verbose=0)  # evaluate model
    print('Metrics => ', model.metrics_names, score)
    y_predict = np.asarray(model.predict(X_test, verbose=0))
    Y_predict = np.argmax(y_predict, axis=1)
    y_test = np.argmax(Y_test, axis=1)
    confmatrix = confusion_matrix(y_test, Y_predict)
    print("\nConfusion Matrix :")
    print(confmatrix)
    class_names = ["0", "1", '2']
    print("\nMetrics => ", model.metrics_names, score)
    print('\nClassification Report : ')
    print(classification_report(y_test, Y_predict, target_names=class_names))
    # save model tested with loss and accuracy
    model.save(path_thebest+'model-'+'{:.4f}'.format(score[0])+'-'+'{:.4f}'.format(score[1])+'.h5')

In [14]:
print('STARTING FITTING NEURAL NETWORK')
if os.path.exists(path_best):
    shutil.rmtree(path_best)
os.mkdir(path_best)
if not os.path.exists(path_thebest):
    os.mkdir(path_thebest)

X_train, X_test, Y_train, Y_test = load_data_nn()

print('loading data .......')

STARTING FITTING NEURAL NETWORK
loading data .......


In [15]:
# generation kfolds to cross validation process
kfold = KFold(n_splits=n_splits, shuffle=True, random_state=seed)
cvscores = []
i = 0

# start cross validation
for train, test in kfold.split(X_train, Y_train):
    model = baseline_model()
    model.fit(X_train[train], Y_train[train], epochs=num_epochs, batch_size=batch_size, verbose=0,
              callbacks=[TensorBoard(log_dir='./nn/tensorboard/'),
                         ModelCheckpoint(path_best+'checkpoint-%d.h5' %(i), monitor='acc', verbose=0,
                                         save_best_only=True, mode='max'),
                         EarlyStopping(monitor='loss', min_delta=0.001, patience=10, verbose=2, mode='min')])
    scores = model.evaluate(X_train[test], Y_train[test], verbose=2)
    print("%s: %.2f%%" % (model.metrics_names[1], scores[1]*100))
    cvscores.append(scores[1] * 100)
    i += 1
print("%.2f%% (+/- %.2f%%)" % (np.mean(cvscores), np.std(cvscores)))

Epoch 00052: early stopping
acc: 96.13%
Epoch 00041: early stopping
acc: 97.50%
Epoch 00056: early stopping
acc: 95.76%
Epoch 00037: early stopping
acc: 96.88%
Epoch 00037: early stopping
acc: 96.50%
Epoch 00054: early stopping
acc: 96.25%
Epoch 00031: early stopping
acc: 94.51%
Epoch 00046: early stopping
acc: 96.88%
Epoch 00041: early stopping
acc: 96.38%
Epoch 00056: early stopping
acc: 97.25%
96.40% (+/- 0.81%)
Load best model and test it 
Metrics =>  ['loss', 'acc'] [0.095308599793494528, 0.96855895196506547]

Confusion Matrix :
[[1077    0    1]
 [  18    7    1]
 [  34    0    7]]

Metrics =>  ['loss', 'acc'] [0.095308599793494528, 0.96855895196506547]

Classification Report : 
             precision    recall  f1-score   support

          0       0.95      1.00      0.98      1078
          1       1.00      0.27      0.42        26
          2       0.78      0.17      0.28        41

avg / total       0.95      0.95      0.94      1145



In [16]:
# evaluate best model based on higher accuracy
vect_max = np.argmax(cvscores)
evaluete_nn(X_test, Y_test, vect_max)

Load best model and test it 
Metrics =>  ['loss', 'acc'] [0.095308599793494528, 0.96855895196506547]

Confusion Matrix :
[[1077    0    1]
 [  18    7    1]
 [  34    0    7]]

Metrics =>  ['loss', 'acc'] [0.095308599793494528, 0.96855895196506547]

Classification Report : 
             precision    recall  f1-score   support

          0       0.95      1.00      0.98      1078
          1       1.00      0.27      0.42        26
          2       0.78      0.17      0.28        41

avg / total       0.95      0.95      0.94      1145

